#!/usr/bin/env bash
#0. World wide web
#giaasdass
function echo_function {
	 echo The subdomain "$1" is a "$3" record and points to "$2"
}
if [[ "$#" = 1 ]]; then
   # display information about subdomains.
   sd=(www lb-01 web-01 web-02)
   for i in "${sd[@]}"; do
       address=$(dig $i."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
       record=$(dig $i."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{printf $5}')
       echo_function "$i" "$address" "$record"
   done
elif [[ "$#" = 2 ]]; then
     # display information about subdomains and domains
     address=$(dig $2."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
     record=$(dig $2."$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf ("%s", $5)}')
     echo_function "$2" "$address" "$record"
fi
