#!/usr/bin/env bash
# Bash script that configure the nginx


sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" > /var/www/html/index.html
