#!/usr/bin/env bash
#install haproxy

apt update
apt install -y haproxy=1.6.\*

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3290-web-01 35.237.241.192 check
    server 3290-web-02 34.139.46.240 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
