#!/usr/bin/env bash
#install haproxy

apt update
sudo apt install haproxy

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3290-web-01 34.138.247.205:80 check
    server 3290-web-02 34.74.60.97:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
