#!/usr/bin/env bash
# Write a Bashdisplays Best School 10 times,9th iteration HI

count=0
eight=8
ten=10
while [ "$count" -lt "$ten" ]; do
	echo "Best School"
	if [ "$count" -eq "$eight" ]
	then
	echo "Hi"
	fi
	((count++))
done
