#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes

horas=0
minutes=1
while [ "$horas" -le 12 ]
do
	echo "Hour: $horas"
	while [ "$minutes" -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((horas++))
done
