#!/usr/bin/env bash
#7 lines or less

chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites_available/default
pkill -f apache2
sudo -u nginx service nginx start
